export const translations = {
  en: {
    welcome1: "Welcome, I’m SARA!",
    welcome2: "Ask me for information about UIU",
    userName: "Guest User",
    getStartedBtnText: "Get Started",
    stepText: "Step",
    stepNum1: "1",
    stepNum2: "2",
    takePhotoBtnText: "Take Photo",
    retakePhotoBtnText: "Retake Photo",
    continuePhotoBtnText: "Next Step",
    loginText: "Tap the mic button to ask question",
    conversationTitle: "Conversation",
    listening: "I am listening",
    nameInputTopText: "Full Name",
    nameInputLabel: "Name",
    nameInputPlaceHolder: "Tap mic to input your name",
    languageSelectLabel: "Select Language",
    step2WarningText:
      'Notice: By tapping "Start", you agree with the "Terms & Conditions" and "Privacy Policy"',
    step2ButtonLabel: "Start",
    feedbackText1: "Your opinion matters",
    feedbackText2: "Help Us Improve!",
    feedbackText3:
      "Share your thoughts and ideas to shape a better experience, we’re listening to you!",
    feedbackText4: "Detail thoughts",
    feedbackBackBtnText: "Back",
    feedbackNextBtnText: "Next",
    feedbackQuestions: [
      "How satisfied are you with the accuracy of the face recognition feature in recognizing you?",
      "How satisfied are you with the system's accuracy in understanding your questions?",
      "How satisfied are you with the clarity of the Text-to-Speech voice when the system responded to you?",
      "How satisfied are you with the accuracy of the responses you received?",
      "How satisfied are you with the system's response time?",
      "How satisfied are you with the ease of navigating through the system?",
      "How satisfied are you with your overall experience using the Smart Reception System compared to a human receptionist?",
    ],
  },
  bn: {
    welcome1: "স্বাগতম,আমি সারা! ইউআইইউ ",
    welcome2: "সম্পর্কে জানতে  জিজ্ঞাসা করুন",
    userName: "নতুন ব্যবহারকারী",
    getStartedBtnText: "শুরু করুন",
    stepText: "ধাপ",
    stepNum1: "১",
    stepNum2: "২",
    takePhotoBtnText: "ছবি তুলুন",
    retakePhotoBtnText: "পুনরায় ছবি তুলুন",
    continuePhotoBtnText: "পরবর্তী ধাপে যান",
    loginText: "মাইক বাটনে ট্যাপ করে প্রশ্ন করুন",
    conversationTitle: "কথোপকথন",
    listening: "আমি শ্রবণ করছি",
    nameInputTopText: "সম্পূর্ণ নাম",
    nameInputLabel: "নাম",
    nameInputPlaceHolder: "মাইক্রোফোন ট্যাপ করে নাম বলুন",
    languageSelectLabel: "ভাষা নির্ধারণ করুন ",
    step2WarningText:
      'বিঃদ্রঃ "শুরু করুন" বাটন চাপার মাধ্যমে আপনি আমাদের শর্তাবলী এবং গোপনীয়তা নীতির সাথে সম্মত হচ্ছেন ',
    step2WarningText2: "Terms & Conditions",
    step2WarningText3: "Privacy Policy",
    step2ButtonLabel: "শুরু করুন",
    feedbackText1: "আপনার মতামত গুরুত্বপূর্ণ",
    feedbackText2: "আমাদের উন্নতি করতে সাহায্য করুন!",
    feedbackText3:
      "আরও উন্নত সিস্টেম গঠনের জন্য আপনার চিন্তাভাবনা এবং ধারণাগুলি জানান",
    feedbackText4: "বিস্তারিত মতামত",
    feedbackBackBtnText: "পূর্ববর্তী",
    feedbackNextBtnText: "পরবর্তী",
    feedbackQuestions: [
      "ফেস রিকগনিশন ফিচারটি নিয়ে আপনি কতটা সন্তুষ্ট?",
      "আপনি যে প্রশ্নটি করেছিলেন, সেটি সিস্টেম কতটা সঠিকভাবে বুঝেছে?",
      "টেক্সট-টু-স্পিচ ফিচারটি নিয়ে আপনি কতটা সন্তুষ্ট?",
      "আপনি যে উত্তরগুলি পেয়েছেন, সেগুলির সঠিকতা নিয়ে আপনি কতটা সন্তুষ্ট?",
      "সিস্টেমের উত্তর দেয়ার জন্য নেয়া সময় নিয়ে আপনি কতটা সন্তুষ্ট?",
      "সিস্টেমের মাধ্যমে নেভিগেট করা কতটা সহজ ছিল?",
      "একজন মানব রিসেপশনিস্টের তুলনায় স্মার্ট রিসেপশন সিস্টেম ব্যবহারের আপনার সামগ্রিক অভিজ্ঞতা কেমন?",
    ],
  },
};

export const banglaDays = {
  Sunday: "রবিবার",
  Monday: "সোমবার",
  Tuesday: "মঙ্গলবার",
  Wednesday: "বুধবার",
  Thursday: "বৃহস্পতিবার",
  Friday: "শুক্রবার",
  Saturday: "শনিবার",
};

export const banglaMonths = {
  January: "জানুয়ারি",
  February: "ফেব্রুয়ারি",
  March: "মার্চ",
  April: "এপ্রিল",
  May: "মে",
  June: "জুন",
  July: "জুলাই",
  August: "আগস্ট",
  September: "সেপ্টেম্বর",
  October: "অক্টোবর",
  November: "নভেম্বর",
  December: "ডিসেম্বর",
};

export const banglaDigits = ["০", "১", "২", "৩", "৪", "৫", "৬", "৭", "৮", "৯"];

export const initState = {
  userInFront: false,
  currentPage: "Start",
  currentImageData: null,
  currentLanguage: "bn",
  currentNameData: null,
  userId: null,
  userName: "",
  userNameEn: "",
  currentQuestionData: "",
  messages: [],
  audioPlayDone: false,
  currentRatingValue: 1,
  currentRatingDetailData: null,
  notificationStates: {
    showNotification: false,
    notificationType: "",
    notificationMessage: "",
    processingAudio: false,
  },
  pageStates: {
    startStates: {
      btnPressed: false,
    },
    getStartedStates: {
      getStartedBtnPressed: false,
      micBtnPressed: false,
      showMicToolTip: false,
      welcomeAudioPlayDone: false,
    },
    ConversationStates: {
      micBtnPressed: false,
      showThankYou: false,
    },
  },
  componentStates: {
    getStartedModalStates: {
      openModal: false,
      currentStep: 1,
      faceComponentContinueBtnPressed: false,
      showContinueToolTip: false,
      nameAudioProcessing: false,
      retakeContinueAudioPlayed: false,
    },
    feedbackStates: {
      showFeedbackModal: false,
      listeningStart: false,
      listeningEnd: false,
      currentFeedbackItem: 0,
      allFeedbackStates: [
        {
          emojiRating: 1,
          detail: "",
        },
        {
          emojiRating: 1,
          detail: "",
        },
        {
          emojiRating: 1,
          detail: "",
        },
        {
          emojiRating: 1,
          detail: "",
        },
        {
          emojiRating: 1,
          detail: "",
        },
        {
          emojiRating: 1,
          detail: "",
        },
        {
          emojiRating: 1,
          detail: "",
        },
      ],
    },
  },
};
